language: node_js
node_js:
  - "8"
dist: trusty
services:
  - postgresql
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
      - node_modules
install:
  - npm install
before_script:
  - cp /database.yml.travis /database.yml  
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
